DROP TABLE IMG_CATEGORIES;

CREATE CACHED TABLE IMG_CATEGORIES (
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR,
	PARENT INTEGER,
	COMMENTS VARCHAR
);

INSERT INTO IMG_CATEGORIES VALUES (NULL, 'Images', NULL, NULL);

DROP TABLE IMAGES;

CREATE CACHED TABLE IMAGES (
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR,
	PARENT INTEGER,
	COMMENTS VARCHAR,
	IMAGE_TYPE INTEGER	
);

DROP TABLE FOLDERS;

CREATE CACHED TABLE FOLDERS (
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR,
	PARENT INTEGER,
	IS_ROOT BOOLEAN DEFAULT FALSE	
);

DROP TABLE FILES;

CREATE CACHED TABLE FILES (
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR,
	PARENT INTEGER,
	IS_ROOT BOOLEAN DEFAULT FALSE
);

